### ISSUE TITLE
random

### ISSUE THREAD

**Issue by denisdemais** [JandCandO/Lua_Encryption_Code#1]
Hi

do you can uses a math.randomseed() function at start because math.random() in lua allways generate the same sequence.

--editables START
[...]
math.randomseed( 123123123123123 );
--editables END

with this minimal line a user can 'generate' a more strong otp

**Comment by JandCandO** [comment]
This looks like a good feature to add in, thanks for the tip!

**Comment by JandCandO** [comment]
I'm making the default seed equal to os.time()
